version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: pg_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    

  api-library:
    build:
      context: .
    restart: on-failure
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/library_db
    depends_on:
      - postgres
